apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: demo-gateway
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: backend

