apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zitadel
  template:
    metadata:
      labels:
        app: zitadel
    spec:
      containers:
        - name: zitadel
          image: ghcr.io/zitadel/zitadel:latest
          ports:
            - containerPort: 8080

